language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -q -e .
  - pip install pytest coverage coveralls --use-mirrors
script: coverage run --source=rex py.test
after_success:
  - coveralls
